
services:

  orchware.frontoffice.api:
    image: ${DOCKER_REGISTRY-}orchwarefrontofficeapi:latest
    container_name: orchware.frontoffice.api
    build:
      context: .
      dockerfile: src/Frontoffice/Orchware.Frontoffice.API/Dockerfile
    depends_on:
      - mssql
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orchware.backoffice.api:
    image: ${DOCKER_REGISTRY-}orchwarebackofficeapi:latest
    container_name: orchware.backoffice.api
    build:
      context: .
      dockerfile: src/Backoffice/Orchware.Backoffice.API/Dockerfile
    depends_on:
      - mssql
    restart: always
    ports:
      - "9090:9090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/Backoffice/Orchware.Backoffice.Infrastructure/Persistence/SeedFiles/Shelf.csv:/app/Persistence/SeedFiles/Shelf.csv
      - ./src/Backoffice/Orchware.Backoffice.Infrastructure/Persistence/SeedFiles/Product.csv:/app/Persistence/SeedFiles/Product.csv

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=aJkulAdRakula#123
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata: