@Orchware.Frontoffice.API_HostAddress = http://localhost:5262

POST {{Orchware.Frontoffice.API_HostAddress}}/api/products
Accept: application/json
Content-Type: application/json
{
  "pageIndex": 1,
  "pageSize": 10,
  "orderBy": "Price",
  "orderDirection": "ASC"
}

###
# Get All Seasonal Fruits
GET {{Orchware.Frontoffice.API_HostAddress}}/api/products/seasonal-fruits
Accept: application/json

###
# Get All Units of Measure
GET {{Orchware.Frontoffice.API_HostAddress}}/api/products/units-of-measure
Accept: application/json